version: "3.8"
services:
  neko:
    image: wanjohiryan/qwantify:latest
    restart: "unless-stopped"
    # shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    volumes:
      - /games:/games
    deploy:
      resources:
        reservations:
          devices:
            capabilities: [gpu]
        limits:
          memory: 5G
          cpus: '4' #for testing purposes only
    environment:
      - NEKO_SCREEN=1920x1080@30
      - NEKO_PASSWORD=neko
      - NEKO_PASSWORD_ADMIN=admin
      - NEKO_EPR=52000-52100
      - NEKO_ICELITE=1
      - APPPATH=/path/to/game/folder
      - APPFILE=/game.exe