name: "Build docker image"

on:
  push:
    branches: [ master ]
  #
  # Run this action periodically to keep browsers up-to-date
  # even if there is no activity in this repo.
  #
  schedule:
    - cron: "43 2 * * 1"
  # run it during pull request
  pull_request:

jobs:
  build-git-package:
    runs-on: ubuntu-latest
    #
    # do not run on forks
    #
    if: github.repository_owner == 'wanjohiryan'
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
      
      - name: Move Dockerfile to base
        run: |
            cp ./gamevm/base/Dockerfile ./

      - name: Build image and push to Docker Hub and GitHub Container Registry
        run: |
          docker build . --tag ghrc.io/wanjohiryan/qwantify:latest
          docker run ghrc.io/wanjohiryan/qwantify:latest
          docker push ghrc.io/wanjohiryan/qwantify:latest
